# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /sNow/IH/centos/7.3.1611/SandyBridge/software/CMake/3.14.4-foss-2016b/bin/cmake

# The command to remove a file.
RM = /sNow/IH/centos/7.3.1611/SandyBridge/software/CMake/3.14.4-foss-2016b/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/projects/energia/developments/oasis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/projects/energia/developments/oasis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/sNow/IH/centos/7.3.1611/SandyBridge/software/CMake/3.14.4-foss-2016b/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/sNow/IH/centos/7.3.1611/SandyBridge/software/CMake/3.14.4-foss-2016b/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/projects/energia/developments/oasis/CMakeFiles /home/projects/energia/developments/oasis/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/projects/energia/developments/oasis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OASIS

# Build rule for target.
OASIS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OASIS
.PHONY : OASIS

# fast build rule for target.
OASIS/fast:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/build
.PHONY : OASIS/fast

src/BCPs/BCPs.o: src/BCPs/BCPs.cpp.o

.PHONY : src/BCPs/BCPs.o

# target to build an object file
src/BCPs/BCPs.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/BCPs/BCPs.cpp.o
.PHONY : src/BCPs/BCPs.cpp.o

src/BCPs/BCPs.i: src/BCPs/BCPs.cpp.i

.PHONY : src/BCPs/BCPs.i

# target to preprocess a source file
src/BCPs/BCPs.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/BCPs/BCPs.cpp.i
.PHONY : src/BCPs/BCPs.cpp.i

src/BCPs/BCPs.s: src/BCPs/BCPs.cpp.s

.PHONY : src/BCPs/BCPs.s

# target to generate assembly for a file
src/BCPs/BCPs.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/BCPs/BCPs.cpp.s
.PHONY : src/BCPs/BCPs.cpp.s

src/BCPs/Winchies.o: src/BCPs/Winchies.cpp.o

.PHONY : src/BCPs/Winchies.o

# target to build an object file
src/BCPs/Winchies.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/BCPs/Winchies.cpp.o
.PHONY : src/BCPs/Winchies.cpp.o

src/BCPs/Winchies.i: src/BCPs/Winchies.cpp.i

.PHONY : src/BCPs/Winchies.i

# target to preprocess a source file
src/BCPs/Winchies.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/BCPs/Winchies.cpp.i
.PHONY : src/BCPs/Winchies.cpp.i

src/BCPs/Winchies.s: src/BCPs/Winchies.cpp.s

.PHONY : src/BCPs/Winchies.s

# target to generate assembly for a file
src/BCPs/Winchies.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/BCPs/Winchies.cpp.s
.PHONY : src/BCPs/Winchies.cpp.s

src/BCPs/WinchiesController.o: src/BCPs/WinchiesController.cpp.o

.PHONY : src/BCPs/WinchiesController.o

# target to build an object file
src/BCPs/WinchiesController.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/BCPs/WinchiesController.cpp.o
.PHONY : src/BCPs/WinchiesController.cpp.o

src/BCPs/WinchiesController.i: src/BCPs/WinchiesController.cpp.i

.PHONY : src/BCPs/WinchiesController.i

# target to preprocess a source file
src/BCPs/WinchiesController.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/BCPs/WinchiesController.cpp.i
.PHONY : src/BCPs/WinchiesController.cpp.i

src/BCPs/WinchiesController.s: src/BCPs/WinchiesController.cpp.s

.PHONY : src/BCPs/WinchiesController.s

# target to generate assembly for a file
src/BCPs/WinchiesController.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/BCPs/WinchiesController.cpp.s
.PHONY : src/BCPs/WinchiesController.cpp.s

src/Bodies/Bodies.o: src/Bodies/Bodies.cpp.o

.PHONY : src/Bodies/Bodies.o

# target to build an object file
src/Bodies/Bodies.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Bodies/Bodies.cpp.o
.PHONY : src/Bodies/Bodies.cpp.o

src/Bodies/Bodies.i: src/Bodies/Bodies.cpp.i

.PHONY : src/Bodies/Bodies.i

# target to preprocess a source file
src/Bodies/Bodies.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Bodies/Bodies.cpp.i
.PHONY : src/Bodies/Bodies.cpp.i

src/Bodies/Bodies.s: src/Bodies/Bodies.cpp.s

.PHONY : src/Bodies/Bodies.s

# target to generate assembly for a file
src/Bodies/Bodies.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Bodies/Bodies.cpp.s
.PHONY : src/Bodies/Bodies.cpp.s

src/CommonTools.o: src/CommonTools.cpp.o

.PHONY : src/CommonTools.o

# target to build an object file
src/CommonTools.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/CommonTools.cpp.o
.PHONY : src/CommonTools.cpp.o

src/CommonTools.i: src/CommonTools.cpp.i

.PHONY : src/CommonTools.i

# target to preprocess a source file
src/CommonTools.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/CommonTools.cpp.i
.PHONY : src/CommonTools.cpp.i

src/CommonTools.s: src/CommonTools.cpp.s

.PHONY : src/CommonTools.s

# target to generate assembly for a file
src/CommonTools.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/CommonTools.cpp.s
.PHONY : src/CommonTools.cpp.s

src/Exceptions/Exception.o: src/Exceptions/Exception.cpp.o

.PHONY : src/Exceptions/Exception.o

# target to build an object file
src/Exceptions/Exception.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Exceptions/Exception.cpp.o
.PHONY : src/Exceptions/Exception.cpp.o

src/Exceptions/Exception.i: src/Exceptions/Exception.cpp.i

.PHONY : src/Exceptions/Exception.i

# target to preprocess a source file
src/Exceptions/Exception.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Exceptions/Exception.cpp.i
.PHONY : src/Exceptions/Exception.cpp.i

src/Exceptions/Exception.s: src/Exceptions/Exception.cpp.s

.PHONY : src/Exceptions/Exception.s

# target to generate assembly for a file
src/Exceptions/Exception.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Exceptions/Exception.cpp.s
.PHONY : src/Exceptions/Exception.cpp.s

src/Hydro/CumminsIrregular.o: src/Hydro/CumminsIrregular.cpp.o

.PHONY : src/Hydro/CumminsIrregular.o

# target to build an object file
src/Hydro/CumminsIrregular.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Hydro/CumminsIrregular.cpp.o
.PHONY : src/Hydro/CumminsIrregular.cpp.o

src/Hydro/CumminsIrregular.i: src/Hydro/CumminsIrregular.cpp.i

.PHONY : src/Hydro/CumminsIrregular.i

# target to preprocess a source file
src/Hydro/CumminsIrregular.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Hydro/CumminsIrregular.cpp.i
.PHONY : src/Hydro/CumminsIrregular.cpp.i

src/Hydro/CumminsIrregular.s: src/Hydro/CumminsIrregular.cpp.s

.PHONY : src/Hydro/CumminsIrregular.s

# target to generate assembly for a file
src/Hydro/CumminsIrregular.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Hydro/CumminsIrregular.cpp.s
.PHONY : src/Hydro/CumminsIrregular.cpp.s

src/Hydro/CumminsRegular.o: src/Hydro/CumminsRegular.cpp.o

.PHONY : src/Hydro/CumminsRegular.o

# target to build an object file
src/Hydro/CumminsRegular.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Hydro/CumminsRegular.cpp.o
.PHONY : src/Hydro/CumminsRegular.cpp.o

src/Hydro/CumminsRegular.i: src/Hydro/CumminsRegular.cpp.i

.PHONY : src/Hydro/CumminsRegular.i

# target to preprocess a source file
src/Hydro/CumminsRegular.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Hydro/CumminsRegular.cpp.i
.PHONY : src/Hydro/CumminsRegular.cpp.i

src/Hydro/CumminsRegular.s: src/Hydro/CumminsRegular.cpp.s

.PHONY : src/Hydro/CumminsRegular.s

# target to generate assembly for a file
src/Hydro/CumminsRegular.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Hydro/CumminsRegular.cpp.s
.PHONY : src/Hydro/CumminsRegular.cpp.s

src/Hydro/HydroDatabase.o: src/Hydro/HydroDatabase.cpp.o

.PHONY : src/Hydro/HydroDatabase.o

# target to build an object file
src/Hydro/HydroDatabase.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Hydro/HydroDatabase.cpp.o
.PHONY : src/Hydro/HydroDatabase.cpp.o

src/Hydro/HydroDatabase.i: src/Hydro/HydroDatabase.cpp.i

.PHONY : src/Hydro/HydroDatabase.i

# target to preprocess a source file
src/Hydro/HydroDatabase.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Hydro/HydroDatabase.cpp.i
.PHONY : src/Hydro/HydroDatabase.cpp.i

src/Hydro/HydroDatabase.s: src/Hydro/HydroDatabase.cpp.s

.PHONY : src/Hydro/HydroDatabase.s

# target to generate assembly for a file
src/Hydro/HydroDatabase.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Hydro/HydroDatabase.cpp.s
.PHONY : src/Hydro/HydroDatabase.cpp.s

src/Lines/Lines_Dyn.o: src/Lines/Lines_Dyn.cpp.o

.PHONY : src/Lines/Lines_Dyn.o

# target to build an object file
src/Lines/Lines_Dyn.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Lines/Lines_Dyn.cpp.o
.PHONY : src/Lines/Lines_Dyn.cpp.o

src/Lines/Lines_Dyn.i: src/Lines/Lines_Dyn.cpp.i

.PHONY : src/Lines/Lines_Dyn.i

# target to preprocess a source file
src/Lines/Lines_Dyn.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Lines/Lines_Dyn.cpp.i
.PHONY : src/Lines/Lines_Dyn.cpp.i

src/Lines/Lines_Dyn.s: src/Lines/Lines_Dyn.cpp.s

.PHONY : src/Lines/Lines_Dyn.s

# target to generate assembly for a file
src/Lines/Lines_Dyn.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Lines/Lines_Dyn.cpp.s
.PHONY : src/Lines/Lines_Dyn.cpp.s

src/Lines/Lines_QS.o: src/Lines/Lines_QS.cpp.o

.PHONY : src/Lines/Lines_QS.o

# target to build an object file
src/Lines/Lines_QS.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Lines/Lines_QS.cpp.o
.PHONY : src/Lines/Lines_QS.cpp.o

src/Lines/Lines_QS.i: src/Lines/Lines_QS.cpp.i

.PHONY : src/Lines/Lines_QS.i

# target to preprocess a source file
src/Lines/Lines_QS.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Lines/Lines_QS.cpp.i
.PHONY : src/Lines/Lines_QS.cpp.i

src/Lines/Lines_QS.s: src/Lines/Lines_QS.cpp.s

.PHONY : src/Lines/Lines_QS.s

# target to generate assembly for a file
src/Lines/Lines_QS.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Lines/Lines_QS.cpp.s
.PHONY : src/Lines/Lines_QS.cpp.s

src/MathTools.o: src/MathTools.cpp.o

.PHONY : src/MathTools.o

# target to build an object file
src/MathTools.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/MathTools.cpp.o
.PHONY : src/MathTools.cpp.o

src/MathTools.i: src/MathTools.cpp.i

.PHONY : src/MathTools.i

# target to preprocess a source file
src/MathTools.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/MathTools.cpp.i
.PHONY : src/MathTools.cpp.i

src/MathTools.s: src/MathTools.cpp.s

.PHONY : src/MathTools.s

# target to generate assembly for a file
src/MathTools.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/MathTools.cpp.s
.PHONY : src/MathTools.cpp.s

src/ODE_solvers/ODE_solvers.o: src/ODE_solvers/ODE_solvers.cpp.o

.PHONY : src/ODE_solvers/ODE_solvers.o

# target to build an object file
src/ODE_solvers/ODE_solvers.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/ODE_solvers/ODE_solvers.cpp.o
.PHONY : src/ODE_solvers/ODE_solvers.cpp.o

src/ODE_solvers/ODE_solvers.i: src/ODE_solvers/ODE_solvers.cpp.i

.PHONY : src/ODE_solvers/ODE_solvers.i

# target to preprocess a source file
src/ODE_solvers/ODE_solvers.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/ODE_solvers/ODE_solvers.cpp.i
.PHONY : src/ODE_solvers/ODE_solvers.cpp.i

src/ODE_solvers/ODE_solvers.s: src/ODE_solvers/ODE_solvers.cpp.s

.PHONY : src/ODE_solvers/ODE_solvers.s

# target to generate assembly for a file
src/ODE_solvers/ODE_solvers.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/ODE_solvers/ODE_solvers.cpp.s
.PHONY : src/ODE_solvers/ODE_solvers.cpp.s

src/SEM_math/quadrule.o: src/SEM_math/quadrule.cpp.o

.PHONY : src/SEM_math/quadrule.o

# target to build an object file
src/SEM_math/quadrule.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/SEM_math/quadrule.cpp.o
.PHONY : src/SEM_math/quadrule.cpp.o

src/SEM_math/quadrule.i: src/SEM_math/quadrule.cpp.i

.PHONY : src/SEM_math/quadrule.i

# target to preprocess a source file
src/SEM_math/quadrule.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/SEM_math/quadrule.cpp.i
.PHONY : src/SEM_math/quadrule.cpp.i

src/SEM_math/quadrule.s: src/SEM_math/quadrule.cpp.s

.PHONY : src/SEM_math/quadrule.s

# target to generate assembly for a file
src/SEM_math/quadrule.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/SEM_math/quadrule.cpp.s
.PHONY : src/SEM_math/quadrule.cpp.s

src/Simulations/Simulation.o: src/Simulations/Simulation.cpp.o

.PHONY : src/Simulations/Simulation.o

# target to build an object file
src/Simulations/Simulation.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Simulations/Simulation.cpp.o
.PHONY : src/Simulations/Simulation.cpp.o

src/Simulations/Simulation.i: src/Simulations/Simulation.cpp.i

.PHONY : src/Simulations/Simulation.i

# target to preprocess a source file
src/Simulations/Simulation.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Simulations/Simulation.cpp.i
.PHONY : src/Simulations/Simulation.cpp.i

src/Simulations/Simulation.s: src/Simulations/Simulation.cpp.s

.PHONY : src/Simulations/Simulation.s

# target to generate assembly for a file
src/Simulations/Simulation.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Simulations/Simulation.cpp.s
.PHONY : src/Simulations/Simulation.cpp.s

src/Spring/Spring.o: src/Spring/Spring.cpp.o

.PHONY : src/Spring/Spring.o

# target to build an object file
src/Spring/Spring.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Spring/Spring.cpp.o
.PHONY : src/Spring/Spring.cpp.o

src/Spring/Spring.i: src/Spring/Spring.cpp.i

.PHONY : src/Spring/Spring.i

# target to preprocess a source file
src/Spring/Spring.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Spring/Spring.cpp.i
.PHONY : src/Spring/Spring.cpp.i

src/Spring/Spring.s: src/Spring/Spring.cpp.s

.PHONY : src/Spring/Spring.s

# target to generate assembly for a file
src/Spring/Spring.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Spring/Spring.cpp.s
.PHONY : src/Spring/Spring.cpp.s

src/Waves/RegularWave.o: src/Waves/RegularWave.cpp.o

.PHONY : src/Waves/RegularWave.o

# target to build an object file
src/Waves/RegularWave.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Waves/RegularWave.cpp.o
.PHONY : src/Waves/RegularWave.cpp.o

src/Waves/RegularWave.i: src/Waves/RegularWave.cpp.i

.PHONY : src/Waves/RegularWave.i

# target to preprocess a source file
src/Waves/RegularWave.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Waves/RegularWave.cpp.i
.PHONY : src/Waves/RegularWave.cpp.i

src/Waves/RegularWave.s: src/Waves/RegularWave.cpp.s

.PHONY : src/Waves/RegularWave.s

# target to generate assembly for a file
src/Waves/RegularWave.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/Waves/RegularWave.cpp.s
.PHONY : src/Waves/RegularWave.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/os_tools.o: src/os_tools.cpp.o

.PHONY : src/os_tools.o

# target to build an object file
src/os_tools.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/os_tools.cpp.o
.PHONY : src/os_tools.cpp.o

src/os_tools.i: src/os_tools.cpp.i

.PHONY : src/os_tools.i

# target to preprocess a source file
src/os_tools.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/os_tools.cpp.i
.PHONY : src/os_tools.cpp.i

src/os_tools.s: src/os_tools.cpp.s

.PHONY : src/os_tools.s

# target to generate assembly for a file
src/os_tools.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/src/os_tools.cpp.s
.PHONY : src/os_tools.cpp.s

version.o: version.cpp.o

.PHONY : version.o

# target to build an object file
version.cpp.o:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/version.cpp.o
.PHONY : version.cpp.o

version.i: version.cpp.i

.PHONY : version.i

# target to preprocess a source file
version.cpp.i:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/version.cpp.i
.PHONY : version.cpp.i

version.s: version.cpp.s

.PHONY : version.s

# target to generate assembly for a file
version.cpp.s:
	$(MAKE) -f CMakeFiles/OASIS.dir/build.make CMakeFiles/OASIS.dir/version.cpp.s
.PHONY : version.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... OASIS"
	@echo "... src/BCPs/BCPs.o"
	@echo "... src/BCPs/BCPs.i"
	@echo "... src/BCPs/BCPs.s"
	@echo "... src/BCPs/Winchies.o"
	@echo "... src/BCPs/Winchies.i"
	@echo "... src/BCPs/Winchies.s"
	@echo "... src/BCPs/WinchiesController.o"
	@echo "... src/BCPs/WinchiesController.i"
	@echo "... src/BCPs/WinchiesController.s"
	@echo "... src/Bodies/Bodies.o"
	@echo "... src/Bodies/Bodies.i"
	@echo "... src/Bodies/Bodies.s"
	@echo "... src/CommonTools.o"
	@echo "... src/CommonTools.i"
	@echo "... src/CommonTools.s"
	@echo "... src/Exceptions/Exception.o"
	@echo "... src/Exceptions/Exception.i"
	@echo "... src/Exceptions/Exception.s"
	@echo "... src/Hydro/CumminsIrregular.o"
	@echo "... src/Hydro/CumminsIrregular.i"
	@echo "... src/Hydro/CumminsIrregular.s"
	@echo "... src/Hydro/CumminsRegular.o"
	@echo "... src/Hydro/CumminsRegular.i"
	@echo "... src/Hydro/CumminsRegular.s"
	@echo "... src/Hydro/HydroDatabase.o"
	@echo "... src/Hydro/HydroDatabase.i"
	@echo "... src/Hydro/HydroDatabase.s"
	@echo "... src/Lines/Lines_Dyn.o"
	@echo "... src/Lines/Lines_Dyn.i"
	@echo "... src/Lines/Lines_Dyn.s"
	@echo "... src/Lines/Lines_QS.o"
	@echo "... src/Lines/Lines_QS.i"
	@echo "... src/Lines/Lines_QS.s"
	@echo "... src/MathTools.o"
	@echo "... src/MathTools.i"
	@echo "... src/MathTools.s"
	@echo "... src/ODE_solvers/ODE_solvers.o"
	@echo "... src/ODE_solvers/ODE_solvers.i"
	@echo "... src/ODE_solvers/ODE_solvers.s"
	@echo "... src/SEM_math/quadrule.o"
	@echo "... src/SEM_math/quadrule.i"
	@echo "... src/SEM_math/quadrule.s"
	@echo "... src/Simulations/Simulation.o"
	@echo "... src/Simulations/Simulation.i"
	@echo "... src/Simulations/Simulation.s"
	@echo "... src/Spring/Spring.o"
	@echo "... src/Spring/Spring.i"
	@echo "... src/Spring/Spring.s"
	@echo "... src/Waves/RegularWave.o"
	@echo "... src/Waves/RegularWave.i"
	@echo "... src/Waves/RegularWave.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/os_tools.o"
	@echo "... src/os_tools.i"
	@echo "... src/os_tools.s"
	@echo "... version.o"
	@echo "... version.i"
	@echo "... version.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

